## This is a conda environment file.
## Use it as follows:
##
##    conda env create -f environment.yml
##
## See https://towardsdatascience.com/a-guide-to-conda-environments-bc6180fc533
## or    https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html
name: sagecoin
channels:
  - conda-forge
  - defaults
dependencies:
  - c-compiler
  - python=3.7.3     # fixed to avoid https://github.com/ContinuumIO/anaconda-issues/issues/11195
  - sage>=8.9
  - pip
  - setuptools
